### ISSUE TITLE
Packet initialization and exceptions

### ISSUE THREAD

**Issue by jimbo1023** [mike01/pypacker#12]
Thanks for the library. There aren't many like it for Python 3 yet.

I'm posting this regarding Packet object initialization in pypacker.py. In there, any exceptions are caught and logged internally. 
```
            except Exception as e:
                # TODO: remove to continue parsing
                # raise Exception("%r" % e)
                logger.exception("could not dissect or unpack: %r" % e)
``` 
(Around line 409 at time of writing)

Would it be possible to have it raise the exception and not pass over it? I'd like to handle them personally if something goes wrong. Maybe to avoid backward compatibility issues, log-and-pass could be the default, but setting a flag could force it to raise the exception?

**Comment by mike01** [comment]
There are some dependencies which would get broken when raising an exception. An attribute "dissect_error" was added which is set to True on any exceptions.
