### ISSUE TITLE
Replace string type with byte type in missed places.

### ISSUE THREAD

**Issue by NazarTkachuk** [mike01/pypacker#16]
Replace string type with byte type for default values in packet field. In certain modules rfb.py, mb.py

Example:
pypacker/pypacker/layer567/smb.py

class SMB(pypacker.Packet):
	__hdr__ = [
		("proto", "4s", b""),
		("cmd", "B", 0),
		("err", "I", 0),
		("flags1", "B", 0),
		("flags2", "B", 0),
		**("pad", "6s", ""), # replace with b""** 
		("tid", "H", 0),
		("pid", "H", 0),
		("uid", "H", 0),
		("mid", "H", 0)
	]

pypacker/pypacker/layer567/rfb.py
class SetPixelFormat(pypacker.Packet):
	__hdr__ = (
		**("pad", "3s", ""), # replace with b""**
		**("pixel_fmt", "16s", "") # replace with b""**
	)

**Comment by mike01** [comment]
Thx, will be merged
