### ISSUE TITLE
Cannot enable promiscuous mode in Linux

### ISSUE THREAD

**Issue by NazarTkachuk** [mike01/pypacker#19]
When try to enable promiscuous mode in Linux via SocketHndl class AttributeError exception is raised.

>>> from pypacker import psocket
>>> sock_l2 = psocket.SocketHndl(iface_name="eth0", promisc=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/src/pypacker/pypacker/psocket.py", line 48, in __init__
    self._socket_recv.setsockopt(socket.SIO_RCVALL, socket.RCVALL_ON)
AttributeError: module 'socket' has no attribute 'SIO_RCVALL'

**Comment by mike01** [comment]
Fixed by removing parameter. Promisc mode is not needed when receiving in MODE_LAYER_2. For MODE_LAYER_3 this can be set using "ifconfig [iface] promisc".
