### ISSUE TITLE
Update Packet __iter__() method

### ISSUE THREAD

**Issue by NazarTkachuk** [mike01/pypacker#21]
Iteration over every layer starting with lowest layer doesn't work. All time first layer is skipped because  _get_bodyhandler() method returns next layer for lowest layer as well.

>>> pkt = ethernet.Ethernet()+ip.IP()+tcp.TCP()
>>> for p in pkt.lowest_layer:
...     print(p)
...
IP(v_hl=45, tos=0, len=28, id=0, off=0, ttl=40, p=6, sum=7AD1, src=b'\x00\x00\x00\x00', dst=b'\x00\x00\x00\x00', opts=[], handler=tcp)
TCP(sport=DEAD, dport=0, seq=DEADBEEF, ack=0, off_x2=50, flags=2, win=FFFF, sum=3398, urp=0, opts=[], bytes=b'')

I created pull request with proposal to start iterate from first layer all time. It makes iteration more flexible.
To skip first layer use upper layer or body handler. See examples below
1. Iterate over every layer
>>> pkt = ethernet.Ethernet()+ip.IP()+tcp.TCP()
>>> for p in pkt:
...     print(p)
...
Ethernet(dst=b'\xff\xff\xff\xff\xff\xff', src=b'\xff\xff\xff\xff\xff\xff', vlan=[], type=800, handler=ip)
IP(v_hl=45, tos=0, len=28, id=0, off=0, ttl=40, p=6, sum=7AD1, src=b'\x00\x00\x00\x00', dst=b'\x00\x00\x00\x00', opts=[], handler=tcp)
TCP(sport=DEAD, dport=0, seq=DEADBEEF, ack=0, off_x2=50, flags=2, win=FFFF, sum=3398, urp=0, opts=[], bytes=b'')

2. Skip first layer
>>> for p in pkt.upper_layer:
...     print(p)
...
IP(v_hl=45, tos=0, len=28, id=0, off=0, ttl=40, p=6, sum=7AD1, src=b'\x00\x00\x00\x00', dst=b'\x00\x00\x00\x00', opts=[], handler=tcp)
TCP(sport=DEAD, dport=0, seq=DEADBEEF, ack=0, off_x2=50, flags=2, win=FFFF, sum=3398, urp=0, opts=[], bytes=b'')

3. Start from highest
>>> for p in pkt.highest_layer:
...     print(p)
...
TCP(sport=DEAD, dport=0, seq=DEADBEEF, ack=0, off_x2=50, flags=2, win=FFFF, sum=3398, urp=0, opts=[], bytes=b'')

Thanks,
Nazar

**Comment by mike01** [comment]
Thanks, pull request got merged
