### ISSUE TITLE
pip installer

### ISSUE THREAD

**Issue by Qeeker** [mike01/pypacker#23]
When I try install pypacker via pip it will end with error message: 
`Could not find a version that satisfies the requirement pypacker (from versions: ) No matching distribution found for pypacker`

I tried it on Linux Manjaro with Python 3.6.0 and on Debian with Python 3.4.2 both end up with the same results.

**Comment by mike01** [comment]
Problem rootet in errors re-uploading the same version. Seems like the pypi guys messed up their API and nobody wants to fix it (https://github.com/pypa/packaging-problems/issues/74). Should work now, tested with Python 3.4
