### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by Muzikbrat** [mike01/pypacker#30]
on running the given example code the following error is showing up
 File "pypacker_exmpls.py", line 1, in <module>
    import pypacker.pypacker as pypacker
  File "/usr/local/lib/python2.7/dist-packages/pypacker/pypacker.py", line 31
    class Packet(object, metaclass=MetaPacket):

**Comment by mike01** [comment]
hmm looks like pypacker got installed using python2.7. It needs python3, when manually installing using setup.py make sure it's called using this version, so something like "python3 setup.py install".

**Comment by Muzikbrat** [comment]
oh ok
Thanks
