### ISSUE TITLE
python2 support

### ISSUE THREAD

**Issue by pstoll** [mike01/pypacker#33]
Any chance you'd consider making this library python2 compatible for those of us stuck on python2?

**Comment by mike01** [comment]
One of the reasons for creating pypacker was python 3 support. Going back to python 2 and keeping the python 2 compatibility is something I don't need in daily work so I personally won't do it. But if someone is willing to integrate it I can create an extra branch for this.

**Comment by mike01** [comment]
Pypacker now has a dedicated branch for python 2.7 compatibility (not maintained by me).
