### ISSUE TITLE
Problem with multiprocessing library

### ISSUE THREAD

**Issue by mraabs** [mike01/pypacker#40]
Hi, I wanted to run the packet interceptor  using multiprocessing, so I wrote the following codes. When I run the 
it it calls the dpi_start function however it doesn't capture any packet.
"""
Interceptor example using ICMP

```
ADD this rule:
sudo iptables -I INPUT 1 -p icmp -j NFQUEUE --queue-balance 0:2
"""
import time
from multiprocessing import Process
import os
from pypacker import interceptor
from pypacker.layer3 import ip

class TrafficMonitor(object):
    # ICMP Echo request intercepting
    def verdict_cb(self, ll_data, ll_proto_id, data, ctx):
        # ip1 = ip.IP(data)
        ip1 = ip.IP(data)


        print('\n---------->Packet recieved:\n\t source ip:%s , the dst ip:%s, \n\npacket_info:%s '
            %(ip1.src_s, ip1.dst_s, ip1))
        return ip1.bin(), interceptor.NF_ACCEPT

    def dpi_start(self, queue_id):
        print('queue', queue_id)
        ictor = interceptor.Interceptor()
        # queue = [0, 1, 2]
        ictor.start(self.verdict_cb, queue_ids=queue_id)


def start_int():
    monitor = TrafficMonitor()
    proc = Process(target=monitor.dpi_start, args=([0, 1, 2],))
    proc.start()


if __name__ == '__main__':
    while True :
        a = input('press y to start: ')
        if a == 'y':
            start_int()

        elif a == 'x':
            os._exit(0)
```
I tried this also ``` proc = Process(target=ictor.start, args=(self.verdict_cb, [0, 1, 2],)) ``` the same issue persists, it seems the ictor.start is called but no packet is captured. 
However, when I using threading library ```t = Thread(target=ictor.start, args=(self.verdict_cb, [0, 1, 2],))```it works as expected. 

I would like to know if packet interceptor has any issue with multiprocessing or I am doing something wrong.
Thank you

**Comment by mike01** [comment]
Hm interesting, I'm at the 34c3 right know but will check this out as soon as I've time.

**Comment by mike01** [comment]
Ok I just had a look, very easy. You're calling dpi_start(...) via a new process, but that method instantly finished after ictor.start() as it's non blocking. The original code also uses some sleep(...) to allow packet intercepting.

**Comment by mraabs** [comment]
Thank you very much for the solution and your time.
