### ISSUE TITLE
modifying TCP payload

### ISSUE THREAD

**Issue by svolpe** [mike01/pypacker#41]
I'm working on a project where I would like to modify the TCP payload sort of like a man in the middle.  Do you happen to have an example of that?  I tried using the interceptor example but I keep getting 
ERROR (__init__): could not dissect or unpack in IP: TypeError("'NoneType' object is not subscriptable",)
I'm assuming that is because I'm somehow not accounting for layer4 stuff since the interceptor example only works at layer3.  Any advice/ideas your could give me would be greatly appreciated.

**Comment by mike01** [comment]
Without example code it's hard to say what's going wrong. Refering to the interceptor example this should allow to change to TCP payload. 

import time
from pypacker import interceptor
from pypacker.layer3 import ip, icmp
from pypacker.layer4 import tcp

def verdict_cb(ll_data, ll_proto_id, data, ctx):
	ip1 = ip.IP(data)
        if tcp.TCP in ip1: # ip1.tcp is only accessible if it's actually a TCP packet.
           ip1.tcp.body_bytes = b"tcp payload"

	return ip1.bin(), interceptor.NF_ACCEPT

ictor = interceptor.Interceptor()
ictor.start(verdict_cb, queue_ids=[0, 1, 2])
time.sleep(999)
ictor.stop()
`

**Comment by svolpe** [comment]
Thanks for the quick reply.  
I'm getting the following error when I run the script:
```
ERROR (__init__): could not dissect or unpack in IP: TypeError("'NoneType' object is not subscriptable",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pypacker/pypacker.py", line 169, in __init__
    header_len = self._dissect(args[0])
  File "/usr/local/lib/python3.4/dist-packages/pypacker/layer3/ip.py", line 174, in _dissect
    total_header_length = ((buf[0] & 0xf) << 2)
TypeError: 'NoneType' object is not subscriptable
```

Here is a complete set of instructions on how to recreate this ERROR: 
1. Setting up a NF queue on the first computer:
`iptables -I INPUT -p tcp -s 10.0.0.28 -j NFQUEUE --queue-num 1
` 
2. listening on tcp port 1001 using netcat on one computer (10.0.0.27):
`nc -l -p 1001
`
3. Sending string to that port with netcat from a second computer (10.0.0.28):
`echo 'Hello world' | nc   10.0.0.27 1001
`
4. I then took a baby step and modified your script just to print out the payload:
```
import time
from pypacker import interceptor
from pypacker.layer3 import ip, icmp
from pypacker.layer4 import tcp

def verdict_cb(ll_data, ll_proto_id, data):
        ip1 = ip.IP(data)
        if tcp.TCP in ip1: # ip1.tcp is only accessible if it's actually a TCP packet.
                print ("payload: " + str(ip1.tcp.body_bytes))
                #ip1.tcp.body_bytes = b"Goodbye World!"

        return ip1.bin(), interceptor.NF_ACCEPT

ictor = interceptor.Interceptor()
ictor.start(verdict_cb, queue_ids=[1])
time.sleep(999)
ictor.stop()
````

**Comment by svolpe** [comment]
Also I had to remove ctx from:
`def verdict_cb(ll_data, ll_proto_id, data):
`as I was getting this error:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/local/lib/python3.4/dist-packages/pypacker/interceptor.py", line 396, in verdict_callback_ind
    data_ret, verdict = verdict_callback(data, linklayer_protoid, ctx)
TypeError: verdict_cb() missing 1 required positional argument: 'ctx'
```

Just as an additional bit of information, I installed pypacker-4.0.tar.gz using pip in python-3.4.3

**Comment by mike01** [comment]
The pip version is a bit behind, I'd recommend to use the git master branch (ctx was added to allow custom objects to be handed to the callback). data seems to be None because of the old version. If the problem remains, try checking for None like "if data is None" to make sure it really holds parsable bytes.

**Comment by svolpe** [comment]
Using the git version got rid of the crash! However I had to remove the check for TCP for it to work
`if tcp.TCP in ip1: # ip1.tcp is only accessible if it's actually a TCP packet.
`
Also I was a little surprised that my netcat test bed actually generated a total of 5 packets:
```
payload: b'' size: 3
payload: b'' size: 3
payload: b'Hello World!\n' size: 17
payload: b'' size: 3
payload: b'' size: 3
```

I'm assuming that's all the back and forth with TCP.  Is there a way to filter out the all the ones that do not have a payload? I could just do a check on the payload size and filter by that but I thought it might be worth asking if there is a better way?

**Comment by mike01** [comment]
Hm looks like 3-way handshake und shutdown or something similar.
Checking for payload size seems to be the easiest solution. You could also use some Iptables rules and put them before the nfqueue-rule but even that would be more complicated :b

**Comment by svolpe** [comment]
Thanks for all the help.  everything is working great now.  
One more question:  Do you know what happens if pypacker would modify a packet and push it past the normal supported MTU size (1500 bytes)?  Once its handed back to the kernel through libnetfilter_queue will the kernel automatically handle it and split it using normal packet fragmentation?

**Comment by mike01** [comment]
If the packet size exceeds the MTU of the interface (check via ifconfig) there will likely be some exception.

**Comment by svolpe** [comment]
Just tested it, you are correct.  So if I wanted to split a large packet (greater than 1500MTU) in pypacker is there an easy way to copy a packet and modify data in the original and the copied version (1st 1/2 of the data in the original and 2nd 1/2 in the new one). and send both packets?  I know I would have to handle there now being two packets at the other end but that is ok as I can easily do that.

**Comment by svolpe** [comment]
So in short I would like to send the original packet modified and then send a second TCP packet with additional data to the same port and IP address of the original packet.

**Comment by svolpe** [comment]
I've been looking into this more and I think what I really want to do is send a TCP packet with out having to open a socket at the other end. Is this possible?  All the examples I've seen in pypacker require you to open up a socket so I'm assuming there has to be code at the other end to accept the socket.  I would just like to blindly send a TCP packet.

**Comment by mike01** [comment]
Sending network packets without socket? How should that work? Sending custom TCP-packets implies circumventing the kernel network stack which can be done using raw sockets (layer 2 packets). So sending >1500 bytes MTU would look like:
- Open raw socket
- Split large Packet "Ethernet + IP + TCP + payload" in "Ethernet + IP + TCP + payload1" and "Ethernet + IP + TCP + payload2" and send out via raw socket
- Receive everything on the other end via raw sockets.

The network stack on the receiving side will likely generate TCP reset packets which should be blocked using some iptables rules.
But why not simply using standard TCP-sockets for sending large data? Large payloads are automatically/transparently handled via segmentation, no need for custom splitting.

**Comment by svolpe** [comment]
The reason I did not want to use standard TCP sockets is I'm working on a test system (bridged device)  that is doing analysis on the data on one network before it goes out the WAN to another network (providing a service).  It transmits results of the analysis on the same TCP packet. There is then a device at the other end in a bridge mode as well  that strips of the analysis data  and restores the original TCP packet back to its original state and then lets it continue on to the server  providing the service.  

The reason for this approach is so the two bridged devices can talk without having to establish a VPN or open up any additional ports on the network.  They are just piggy backing on the already established connection.  This connection could be a web port or some other standard service.

My plan was to use netfilter_queue at both ends to intercept the TCP data and do the needed adding/deleting data on the packets.

Diagram:
Client --->Bridged device, analysis --->Firewall--->WAN/Cloud--->Firewall--->Bridged device ,remove analysis--->Server

**Comment by mike01** [comment]
Hm ok interesting. Did you try to compress the piggy-bag data before appending (gzip or whatever)? Perhaps the compression ratio is good enough to decrease the size and reaching <=1500 Bytes. Otherwise, the main problem seems to be to differentiate between the two applications "service" and "analysis data"  (in the sense of TCP). Are you able to dictate the source port on the sending side? This seems to be the easiest solution:
Client -> service:sourceport=0-65534 or analysis data:sourceport=65535 -> ... -> server -> iptables rule -> redirect tcp packets with "sourceport=0-65534" to service target port, and "sourceport=65535" to analysis application port.
Otherwise I'd just send custom TCP packets with a specific source port and some sort of sentinel in the TCP payload to filter out those Segments on the receiving side like:
Client -> Ethernet+IP+TCP:sport=12345,payload=MARKER_COUNTER_XXXXX -> ... -> Server:nfqueue ->filter out/handle custom packet (return data, NF_DROP) or allow packet for normal service (return data, NF_ACCEPT). There is a minor risk for collisions as normal service-packets could also have those properties. The segmentation would have to be done custom e.g. by some sort of counter but that can become nasty. I'd try to avoid that.

**Comment by svolpe** [comment]
I can set the source port since I have control over both bridge devices:
If I'm getting what your saying I could do something like this: 

1. Set source port on first bridge (which I do) then open socket to port that main data is going to alread
2. On second bridge device (recieving device) set iptable rule to redirect all data coming from set source port (above) (also take into account IP + destination port too) to a port on the bridge where there is a client listening to get the test data
3. Do the same on the client bridge so the two bridges can talk back and forth

I'm not 100% sure how to do that since the bridge device really does not have its own IP address other than the loopback.  I'll give it a try and see how it works.

**Comment by svolpe** [comment]
Just out of curiosity, when you use multiple queue ids will verdict_cb be called in a reentrant mannor so you could have 3 instances of the verdict_cb function being called at the same time if all 3 queues have data? 
Ref. code:
```
ictor = interceptor.Interceptor()
ictor.start(verdict_cb, queue_ids=[0, 1, 2])
```

**Comment by mike01** [comment]
The callback verdict_cb ist called once per packet (basically a static method) and if there are no additionally side effects (introduced by the developer in this method) then yes it can be called simultaneously (with all queues having data) without problems.

**Comment by mike01** [comment]
Closing due response timeout
