### ISSUE TITLE
pypacker stops working with large amounts of data

### ISSUE THREAD

**Issue by svolpe** [mike01/pypacker#42]
I configured py-packer on two computers. I then transfer a large amount of data between the two computers (100MB).  the Py-packer on the sending computer stops working at random points (4M - 80M). If I stop/start the py-packer code on the sending side it starts working again.  If I stop/start it on the recieving side nothing happens.
Below is the code used on both sides, its pretty much the example from this site.  Its very repeatable but I'm not even sure how to start debugging it since nothing crashes.  Any advice or suggestions for a starting point? I did try doubling the number of queues and I tried having two differnt sets of queues for incoming and out going data.  I made sure to configure the iptables rules to split incoming and outgoing to the different queues as well.
Snippet from when I did the seperate in and out queues
```
ictor.start(verdict_cb, queue_ids=[0, 1, 2, 3])
ictor2.start(verdict_cb, queue_ids=[4, 5, 6, 7])

```
Here is the main code
```
import time
from pypacker import interceptor
from pypacker.layer3 import ip, icmp
from pypacker.layer4 import tcp

# Note I'm not testing if its a TCP packet lbecause the iptables are only routing TCP packets to the queues
def verdict_cb(ll_data, ll_proto_id, data, ctx):
        ip1 = ip.IP(data)
        pktLen = ip1.len
        dataLen = len(ip1.tcp.body_bytes)
        seq = ip1.tcp.seq
        return ip1.bin(), interceptor.NF_ACCEPT

ictor = interceptor.Interceptor()
ictor.start(verdict_cb, queue_ids=[0, 1, 2])
while 1:
    time.sleep(999)

ictor.stop()

```

**Comment by mike01** [comment]
Could be an exception in the verdict callback. I've added an exception handling in the newest master commit which should warn about such problems (packets will now be dropped in this case)

**Comment by svolpe** [comment]
I just updated my py-packer to the latest version.  It still stops sending data after a period and is not giving any errors. Is there anything I need to do to test it?  I'm running on a resource limited target (embedded ARM).  I've monitored its RAM and CPU and have seen no corrilation to them when the pychecker stops passing data. 
Is there any other way I can debug the problem?

**Comment by mike01** [comment]
Well then I assume there is a problem on the sending side. Without code I can't say anything about that.

**Comment by svolpe** [comment]
There is actually no custom code. I'm running apache on the server side hosting 100MB binary file and then use wget on the client side to pull it.  Its just a stress test system to test the implementation of the pypacker on the embedded system.

**Comment by mike01** [comment]
So what's the exact Setup? Something like this?
[PC: wget -> pypacker:nfqueue] -> Network -> [Target: pypacker:nfqueue -> HTTP-server]
Did you make any basic network debugging? Checking traces via wireshark or similar?
Is the conenction reset or timed out? Any error messages anywhere? I can't say anything
without more information.

**Comment by svolpe** [comment]
The network looks like this:
server(apache)->bridge device(py-packer on it)->WAN->client
I have run wireshark and what I'm seeing is everything works great and then, for some reason, the bridge device (running py-packer) stops forwarding the ACKs from the client to the server.  I'm not 100% sure if also stops transmitting data from the server to the client.  I beleive it does as I see the client continually trying to send the same packet but its not coming out the other end of the bridge.  There are tons of retries but nothing gets through the bridge.  After stopping/starting the py-packer on the bridge it starts working again. I tried stopping/starting the py-packer script on the client but that does not recover the problem.  My guess is it must somehow be caused by the limitations of resources on the embedded bridge device but can't seem to find the smoking gun yet.  I was also thinking about using the multiprocessing capabilities in python as it is a quad core ARM device.  My first attempt at doing that with the py-packer interceptor did not work.  I will continue to dig in.  Once I get the multiprocessor working I will share the code for others. Any thoughts on this would be greatly appriciated.

**Comment by svolpe** [comment]
I ran python-netfilterqueue on the same system and I do not experiance the same issue.  I'm not really interested in using that as my approach because py-packer is such a nicer API to use.  

Just to summerize:
I get no errors in the /proc/net/netfilter/nf_log. There is nothing in /var/log/messages.  No errors are coming out of the py-packer program.  I've used wireshark and it looks like communications stops.  The connections are not reset and they just hang (since no packets coming out of the netfilter queues) until they timeout.

Is there anything I can do to debug deeper into py-packer and see where the problem lies?

**Comment by svolpe** [comment]
Following the instructions on "Enlarge receive/send buffers to get max performance."  made a difference, now it does not stall and not recover.  It still has  small stalls but seems to finish 100% of the time.  I've run a 100MB file through it 10 times now.
 What supprises me is increasing the number of queues does not seem to have any effect on the performance.

**Comment by mike01** [comment]
Nice to hear the problem got solved. There can be a multitude of reasons for the "not increasing performance" and the max network bandwidth as bottleneck is just one of them, so hard to say what's going on.

**Comment by mike01** [comment]
Closing due response timeout
