### ISSUE TITLE
Getting data from ICMP protocol

### ISSUE THREAD

**Issue by mdesco18** [mike01/pypacker#45]
I'm trying to get the data from ICMP protocol. From the documentation, accessing the body of a header (such as an IP header containing a UDP packet in the body) you would write 

eth[ip.IP][udp.UDP].sport

but with an ICMP message, the UDP packet is in the body of the IP header in the ICMP and trying something like 

eth[icmp.ICMP][ip.IP][udp.UDP].sport

does not work because it is a NoneType

Any solution?

**Comment by mike01** [comment]
Hi, are you talking about ICMP unreachable packets? Extracting the original Datagram in the packet could be done like

```orig_bts = mypacket[icmp.ICMP.Unreach].body_bytes
ip1 = ip.IP(orig_bts)```

But (based on the specification) the second layer in ip1 will likely be incomplete/just 8 bytes in length so getting the higher layer data should better be done via "ip1.body_bytes"

**Comment by mdesco18** [comment]
Thanks. I may want the source port from the UDP in ip1 but ip1 should be good for now

**Comment by mike01** [comment]
I've added type 11 (TimeExceed) in the newest commit, should be retrievable via mypacket[icmp.ICMP.TimeExceed].

**Comment by mike01** [comment]
Closing due response timeout
